name: "Республика Казахстан"
code: "KZ"
priority: 3
uses_cyrillic: false
min_length: 6
max_length: 9
stop_words: ["TEST", "SAMPLE"]
allow_sequences: true

license_plate_formats:
  - name: "standard_car"
    regex: "^[0-9]{3}[A-Z]{3}[0-9]{2}$"
    description: "Стандартный номер (латиница)"
  - name: "police"
    regex: "^0\d{2}[A-Z]{2}0{2}$"
    description: "Полиция"

valid_characters:
  letters: "ABCEHKMOPTUXY"
  digits: "0123456789"

corrections:
  common_mistakes:
    - {from: "0", to: "O"}
    - {from: "1", to: "I"}
    - {from: "5", to: "S"}
    - {from: "8", to: "B"}
  latin_to_cyrillic: []
  cyrillic_to_latin:
    - {from: "А", to: "A"}
    - {from: "В", to: "B"}
    - {from: "С", to: "C"}
    - {from: "Е", to: "E"}
    - {from: "К", to: "K"}
    - {from: "М", to: "M"}
    - {from: "Н", to: "H"}
    - {from: "О", to: "O"}
    - {from: "Р", to: "P"}
    - {from: "Т", to: "T"}
    - {from: "Х", to: "X"}
    - {from: "У", to: "Y"}
