name: "Российская Федерация"
code: "RU"
priority: 1
use_cyrillic_normalization: true
license_plate_formats:
  - name: "standard_car"
    regex: "^[АВЕКМНОРСТУХ]\d{3}[АВЕКМНОРСТУХ]{2}\d{2,3}$"
    description: "Стандартный автомобильный номер"
  - name: "transit"
    regex: "^[АВЕКМНОРСТУХ]{2}\d{6}$"
    description: "Транзитный номер"
  - name: "trailer"
    regex: "^\d{4}[АВЕКМНОРСТУХ]{2}\d{2,3}$"
    description: "Прицеп"
  - name: "motorcycle"
    regex: "^\d{4}[АВЕКМНОРСТУХ]{2}\d{2,3}$"
    description: "Мотоцикл"
valid_characters:
  letters: "АВЕКМНОРСТУХ"
  digits: "0123456789"
corrections:
  common_mistakes:
    - from: "0"
      to: "О"
    - from: "1"
      to: "Т"
    - from: "3"
      to: "З"
    - from: "4"
      to: "А"
    - from: "8"
      to: "В"
    - from: "9"
      to: "Р"
  latin_to_cyrillic:
    - from: "A"
      to: "А"
    - from: "B"
      to: "В"
    - from: "C"
      to: "С"
    - from: "E"
      to: "Е"
    - from: "H"
      to: "Н"
    - from: "K"
      to: "К"
    - from: "M"
      to: "М"
    - from: "O"
      to: "О"
    - from: "P"
      to: "Р"
    - from: "T"
      to: "Т"
    - from: "X"
      to: "Х"
    - from: "Y"
      to: "У"
